// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNrRfl7CKdb52LPfoxhHsczXlDoPmj94Y',
    appId: '1:951002117636:web:92ae1a70d6883b77af2751',
    messagingSenderId: '951002117636',
    projectId: 'crud-study-2b724',
    authDomain: 'crud-study-2b724.firebaseapp.com',
    storageBucket: 'crud-study-2b724.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu0oSyhGtkyHRPWwxgaAr0RqYWHfb4ZQA',
    appId: '1:951002117636:android:0026a010be7c4607af2751',
    messagingSenderId: '951002117636',
    projectId: 'crud-study-2b724',
    storageBucket: 'crud-study-2b724.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqAOeOUniVm5slTcrJTIS1LJ3tAWFj37k',
    appId: '1:951002117636:ios:e54fc7e41720b72eaf2751',
    messagingSenderId: '951002117636',
    projectId: 'crud-study-2b724',
    storageBucket: 'crud-study-2b724.appspot.com',
    iosClientId: '951002117636-rc2i8nqt8ghja887su3ufmcauao1p6dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqAOeOUniVm5slTcrJTIS1LJ3tAWFj37k',
    appId: '1:951002117636:ios:e54fc7e41720b72eaf2751',
    messagingSenderId: '951002117636',
    projectId: 'crud-study-2b724',
    storageBucket: 'crud-study-2b724.appspot.com',
    iosClientId: '951002117636-rc2i8nqt8ghja887su3ufmcauao1p6dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebaseProject',
  );
}
